// Raze specific names

xx(IngameMenu)
xx(ListMenuItemBloodDripDrawer)
xx(UsermapMenu)
xx(EngineCredits)
xx(EngineCredits2)
xx(CreditsMenu)
xx(MultiMenu)
xx(RazeStatusBar)
xx(zoomsize)
xx(AltHud)

xx(spawnstate)
xx(brokenstate)
xx(breaksound)
xx(fullbright)
xx(spawnsound)
xx(gutsoffset)
xx(falladjustz)
xx(aimoffset)
xx(strength)
xx(autoaimangle)
xx(shootzoffset)
xx(moveclipdist)
xx(jumptoplayer_factor)
xx(justjump1_factor)
xx(justjump2_factor)
xx(windang_factor)
xx(floating_floordist)
xx(floating_ceilingdist)
