// Raze specific names

xx(IngameMenu)
xx(ListMenuItemBloodDripDrawer)
xx(UsermapMenu)
xx(EngineCredits)
xx(EngineCredits2)
xx(CreditsMenu)
xx(MultiMenu)
xx(RazeStatusBar)
xx(zoomsize)
xx(AltHud)

// internal Duke actor classes that need direct checking
xx(DukeMasterSwitch)
xx(DukeTouchplate)
xx(DukeSoundController)
xx(DukeRespawnController)
xx(DukeActivator)
xx(DukeActivatorLocked)
xx(DukeLocator)
xx(DukeGenericDestructible)
xx(DukeGlassPieces)
xx(DukeGlassPieces1)
xx(DukeGlassPieces2)
xx(DukeNaturalLightning)

xx(spawnstate)
xx(brokenstate)
xx(breaksound)
xx(fullbright)
xx(spawnsound)
