CFLAGS=-i=.. -i=..\include -5r -s -orb

OBJS=layer1.obj layer2.obj layer3.obj synth.obj tables.obj mpadec.obj mp3dec.obj

mpadec.lib: $(OBJS)
	%create $^..tmp
	for %i in ($<) do %append $^..tmp +%i
	wlib -b -n $^* @$^..tmp
	erase $^..tmp

mpadec.dll: $(OBJS)
	wlink NAME $@ SYSTEM WIN95 DLL OPTION IMPLIB=mpadecimp.lib FILE { $< } LIBRARY clib3r.lib EXPORT=mpadec.wlib

.c.obj: ; wcc386 $(CFLAGS) -fo=.obj $[@

clean: .SYMBOLIC
	-del $(OBJS) mpadec.lib mpadec.dll mpadecimp.lib mpadecimp.exp *.err

