// list of textures that get referenced directly in game code.
x(ENERGY2)
x(Spark1)
x(Spark2)
x(Playermarker1)
x(Playermarker2)
x(Playermarker3)
x(Playermarker4)
x(Playermarker5)
x(Playermarker6)
x(Playermarker7)
x(Playermarker8)
x(QueenChunk)
x(QueenChunk2)
x(QueenChunk3)
x(AltQueenChunk)
x(TileRamsesWorkTile)
x(Torch1)
x(Torch2)
x(WeaponSpriteSword)
x(WeaponSpriteMummy)
x(WeaponSpriteMagnum)
x(WeaponSpriteM60)
x(WeaponSpriteFlamethrower)
x(AmmoSpriteGrenade)
x(WeaponSpriteCobra)

