-- Use this file like
--  require("lpeg")
--  con_keyword = dofile("con_lang.lua")

return

lpeg.P(false) +
"{" +
"}" +
"action" +
"activatebysector" +
"activatecheat" +
"actor" +
"addammo" +
"addinventory" +
"addkills" +
"addlog" +
"addlogvar" +
"addphealth" +
"addstrength" +
"addvar" +
"addvarvar" +
"addweapon" +
"addweaponvar" +
"ai" +
"andvar" +
"andvarvar" +
"angoff" +
"angoffvar" +
"betaname" +
"break" +
"cactor" +
"calchypotenuse" +
"cansee" +
"canseespr" +
"case" +
"changespritesect" +
"changespritestat" +
"cheatkeys" +
"checkactivatormotion" +
"checkavailinven" +
"checkavailweapon" +
"clearmapstate" +
"clipdist" +
"clipmove" +
"clipmovenoslide" +
"cmenu" +
"copy" +
"cos" +
"count" +
"cstat" +
"cstator" +
"debris" +
"debug" +
"default" +
"define" +
"definecheat" +
"definegamefuncname" +
"definegametype" +
"definelevelname" +
"defineprojectile" +
"definequote" +
"defineskillname" +
"definesound" +
"definevolumename" +
"digitalnumber" +
"digitalnumberz" +
"displayrand" +
"displayrandvar" +
"displayrandvarvar" +
"dist" +
"divvar" +
"divvarvar" +
"dragpoint" +
"dynamicremap" +
"echo" +
"else" +
"enda" +
"endevent" +
"endofgame" +
"ends" +
"endswitch" +
"enhanced" +
"eqspawn" +
"eqspawnvar" +
"eshoot" +
"eshootvar" +
"espawn" +
"espawnvar" +
"eventloadactor" +
"ezshoot" +
"ezshootvar" +
"fall" +
"findnearactor" +
"findnearactor3d" +
"findnearactor3dvar" +
"findnearactorvar" +
"findnearactorz" +
"findnearactorzvar" +
"findnearsprite" +
"findnearsprite3d" +
"findnearsprite3dvar" +
"findnearspritevar" +
"findnearspritez" +
"findnearspritezvar" +
"findotherplayer" +
"findplayer" +
"flash" +
"gamearray" +
"gamestartup" +
"gametext" +
"gametextz" +
"gamevar" +
"getactor" +
"getactorangle" +
"getactorvar" +
"getangle" +
"getangletotarget" +
"getarraysize" +
"getceilzofslope" +
"getcurraddress" +
"getflorzofslope" +
"getincangle" +
"getinput" +
"getkeyname" +
"getlastpal" +
"getplayer" +
"getplayerangle" +
"getplayervar" +
"getpname" +
"getprojectile" +
"getsector" +
"gettextureceiling" +
"gettexturefloor" +
"getthisprojectile" +
"getticks" +
"gettimedate" +
"gettspr" +
"getuserdef" +
"getwall" +
"getzrange" +
"globalsound" +
"globalsoundvar" +
"gmaxammo" +
"guniqhudid" +
"guts" +
"headspritesect" +
"headspritestat" +
"hitradius" +
"hitradiusvar" +
"hitscan" +
"ifaction" +
"ifactioncount" +
"ifactor" +
"ifactornotstayput" +
"ifactorsound" +
"ifai" +
"ifangdiffl" +
"ifawayfromwall" +
"ifbulletnear" +
"ifcansee" +
"ifcanseetarget" +
"ifcanshoottarget" +
"ifceilingdistl" +
"ifclient" +
"ifcount" +
"ifdead" +
"iffloordistl" +
"ifgapzl" +
"ifgotweaponce" +
"ifhitspace" +
"ifhitweapon" +
"ifinouterspace" +
"ifinspace" +
"ifinwater" +
"ifmove" +
"ifmultiplayer" +
"ifnosounds" +
"ifnotmoving" +
"ifonwater" +
"ifoutside" +
"ifp" +
"ifpdistg" +
"ifpdistl" +
"ifphealthl" +
"ifpinventory" +
"ifrespawn" +
"ifrnd" +
"ifserver" +
"ifsound" +
"ifspawnedby" +
"ifspritepal" +
"ifsquished" +
"ifstrength" +
"ifvarand" +
"ifvare" +
"ifvareither" +
"ifvarg" +
"ifvarl" +
"ifvarn" +
"ifvaror" +
"ifvarvarand" +
"ifvarvare" +
"ifvarvareither" +
"ifvarvarg" +
"ifvarvarl" +
"ifvarvarn" +
"ifvarvaror" +
"ifvarvarxor" +
"ifvarxor" +
"ifwasweapon" +
"include" +
"includedefault" +
"inittimer" +
"insertspriteq" +
"jump" +
"killit" +
"ldist" +
"lineintersect" +
"loadmapstate" +
"lockplayer" +
"lotsofglass" +
"mail" +
"mikesnd" +
"minitext" +
"modvar" +
"modvarvar" +
"money" +
"move" +
"movesprite" +
"mulscale" +
"mulvar" +
"mulvarvar" +
"music" +
"myos" +
"myospal" +
"myospalx" +
"myosx" +
"neartag" +
"nextspritesect" +
"nextspritestat" +
"nullop" +
"onevent" +
"operate" +
"operateactivators" +
"operatemasterswitches" +
"operaterespawns" +
"operatesectors" +
"orvar" +
"orvarvar" +
"palfrom" +
"paper" +
"pkick" +
"precache" +
"prevspritesect" +
"prevspritestat" +
"pstomp" +
"qgetsysstr" +
"qspawn" +
"qspawnvar" +
"qsprintf" +
"qstrcat" +
"qstrcpy" +
"qstrlen" +
"qstrncat" +
"qsubstr" +
"quake" +
"quote" +
"randvar" +
"randvarvar" +
"rayintersect" +
"readarrayfromfile" +
"readgamevar" +
"redefinequote" +
"resetactioncount" +
"resetcount" +
"resetplayer" +
"resizearray" +
"respawnhitag" +
"return" +
"rotatepoint" +
"rotatesprite" +
"rotatesprite16" +
"save" +
"savegamevar" +
"savemapstate" +
"savenn" +
"scriptsize" +
"sectclearinterpolation" +
"sectgethitag" +
"sectgetlotag" +
"sectorofwall" +
"sectsetinterpolation" +
"setactor" +
"setactorangle" +
"setactorsoundpitch" +
"setactorvar" +
"setarray" +
"setaspect" +
"setcfgname" +
"setdefname" +
"setgamename" +
"setgamepalette" +
"setinput" +
"setplayer" +
"setplayerangle" +
"setplayervar" +
"setprojectile" +
"setsector" +
"setsprite" +
"setthisprojectile" +
"settspr" +
"setuserdef" +
"setvar" +
"setvarvar" +
"setwall" +
"shiftvarl" +
"shiftvarr" +
"shoot" +
"shootvar" +
"showview" +
"showviewunbiased" +
"sin" +
"sizeat" +
"sizeto" +
"sleeptime" +
"smaxammo" +
"sound" +
"soundonce" +
"soundoncevar" +
"soundvar" +
"spawn" +
"spgethitag" +
"spgetlotag" +
"spriteflags" +
"spritenopal" +
"spritenoshade" +
"spritenvg" +
"spritepal" +
"spriteshadow" +
"sqrt" +
"ssp" +
"startlevel" +
"starttrack" +
"starttrackvar" +
"state" +
"stopactorsound" +
"stopallsounds" +
"stopsound" +
"stopsoundvar" +
"strength" +
"subvar" +
"subvarvar" +
"switch" +
"time" +
"tip" +
"tossweapon" +
"updatesector" +
"updatesectorz" +
"useractor" +
"userquote" +
"wackplayer" +
"whilevarn" +
"whilevarvarn" +
"writearraytofile" +
"xorvar" +
"xorvarvar" +
"zshoot" +
"zshootvar" +
lpeg.P(false)
