//      original index for reference. Raze never uses literal indices anywhere and should not care about the actual numbers
cmd(definelevelname)		// 0
cmd(actor)					// 1
cmd(addammo)				// 2
cmd(ifrnd)					// 3
cmd(enda)					// 4
cmd(ifcansee)				// 5
cmd(ifhitweapon)			// 6
cmd(action)					// 7
cmd(ifpdistl)				// 8
cmd(ifpdistg)				// 9
cmd(else)					// 10
cmd(strength)				// 11
cmd(break)					// 12
cmd(shoot)					// 13
cmd(palfrom)				// 14
cmd(sound)					// 15
cmd(fall)					// 16
cmd(state)					// 17
cmd(ends)					// 18
cmd(define)					// 19
//cmdx(comment, "//")			// 20
cmd(ifai)					// 21
cmd(killit)					// 22
cmd(addweapon)				// 23
cmd(ai)						// 24
cmd(addphealth)				// 25
cmd(ifdead)					// 26
cmd(ifsquished)				// 27
cmd(sizeto)					// 28
cmdx(leftbrace, "{")		// 29
cmdx(rightbrace, "}")		// 30
cmd(spawn)					// 31
cmd(move)					// 32
cmd(ifwasweapon)			// 33
cmd(ifaction)				// 34
cmd(ifactioncount)			// 35
cmd(resetactioncount) 		// 36
cmd(debris)					// 37
cmd(pstomp)					// 38
//cmdx(blockcomment, "/*")	// 39
cmd(cstat)					// 40
cmd(ifmove)					// 41
cmd(resetplayer)			// 42
cmd(ifonwater)				// 43
cmd(ifinwater)				// 44
cmd(ifcanshoottarget) 		// 45
cmd(ifcount)				// 46
cmd(resetcount)				// 47
cmd(addinventory)			// 48
cmd(ifactornotstayput)		// 49
cmd(hitradius)				// 50
cmd(ifp)					// 51
cmd(count)					// 52
cmd(ifactor)				// 53
cmd(music)					// 54
cmd(include)				// 55
cmd(ifstrength)				// 56
cmd(definesound)			// 57
cmd(guts)					// 58
cmd(ifspawnedby)			// 59
cmd(gamestartup)			// 60
cmd(wackplayer)				// 61
cmd(ifgapzl)				// 62
cmd(ifhitspace)				// 63
cmd(ifoutside)				// 64
cmd(ifmultiplayer)			// 65
cmd(operate)				// 66
cmd(ifinspace)				// 67
cmd(debug)					// 68
cmd(endofgame)				// 69
cmd(ifbulletnear)			// 70
cmd(ifrespawn)				// 71
cmd(iffloordistl)			// 72
cmd(ifceilingdistl)			// 73
cmd(spritepal)				// 74
cmd(ifpinventory)			// 75
cmd(betaname)				// 76
cmd(cactor)					// 77
cmd(ifphealthl)				// 78
cmd(definequote)			// 79
cmd(quote)					// 80
cmd(ifinouterspace)			// 81
cmd(ifnotmoving)			// 82
cmd(respawnhitag)		   	// 83
cmd(tip)				   	// 84
cmd(ifspritepal)			// 85
cmd(money)		 			// 86
cmda(feathers, money)		// RR alias
cmd(soundonce)		 		// 87
cmd(addkills)				// 88
cmd(stopsound)				// 89
cmd(ifawayfromwall)			// 90
cmd(ifcanseetarget)			// 91
cmd(globalsound)			// 92
cmd(lotsofglass) 			// 93
cmd(ifgotweaponce) 			// 94
cmd(getlastpal) 			// 95
cmd(pkick)  				// 96
cmd(mikesnd) 				// 97
cmd(useractor)  			// 98
cmd(sizeat)  				// 99
cmd(addstrength) 			// 100
cmd(cstator) 				// 101
cmd(mail) 					// 102
cmd(paper) 					// 103
cmd(tossweapon) 			// 104
cmd(sleeptime) 				// 105
cmd(nullop) 				// 106
cmd(definevolumename) 		// 107
cmd(defineskillname) 		// 108
cmd(ifnosounds) 			// 109
cmd(clipdist) 				// 110
cmd(ifangdiffl) 			// 111

cmd(ifplaybackon)			// World Tour 112

// WW2GI
cmd(gamevar)				// 112
cmd(ifvarl)					// 113
cmd(ifvarg)					// 114
cmd(setvarvar)				// 115
cmd(setvar)					// 116
cmd(addvarvar)				// 117
cmd(addvar)					// 118
cmd(ifvarvarl)				// 119
cmd(ifvarvarg)				// 120
cmd(addlogvar)				// 121
cmd(addlog)					// 122
cmd(onevent)				// 123
cmd(endevent)				// 124
cmd(ifvare)					// 125
cmd(ifvarvare)				// 126

// RR
cmd(ifnocover)				// 110
cmd(ifhittruck)				// 111 
cmd(iftipcow) 				// 112
cmd(isdrunk) 				// 113
cmd(iseat) 					// 114
cmd(destroyit) 				// 115
cmd(larrybird) 				// 116
cmd(strafeleft) 			// 117
cmd(straferight) 			// 118
cmd(ifactorhealthg) 		// 119
cmd(ifactorhealthl) 		// 120
cmd(slapplayer) 			// 121
cmd(ifpdrunk) 				// 122
cmd(tearitup) 				// 123
cmd(smackbubba) 			// 124
cmd(soundtagonce) 			// 125
cmd(soundtag) 				// 126
cmd(ifsoundid) 				// 127
cmd(ifsounddist) 			// 128
cmd(ifonmud) 				// 129
cmd(ifcoop) 				// 130

// RRRA
cmd(ifmotofast) 			// 131
cmd(ifwind) 				// 132
cmd(smacksprite) 			// 133
cmd(ifonmoto) 				// 134
cmd(ifonboat) 				// 135
cmd(fakebubba) 				// 136
cmd(mamatrigger) 			// 137
cmd(mamaspawn) 				// 138
cmd(mamaquake) 				// 139
cmd(mamaend) 				// 141
cmd(newpic) 				// 142
cmd(garybanjo) 				// 143
cmd(motoloopsnd) 			// 144
cmd(ifsizedown) 			// 145
cmd(rndmove) 				// 146

// EDuke 2.x additions
cmd(spgetlotag)				// 127
cmd(spgethitag)				// 128
cmd(sectgetlotag)			// 129
cmd(sectgethitag)			// 130
cmd(ifsound)				// 131
cmd(gettexturefloor)		// 132
cmd(gettextureceiling)		// 133
cmd(gettexturewall)			// 134
cmd(starttrack)				// 135
cmd(randvar)				// 136
cmd(enhanced)				// 137
cmd(getangletotarget)		// 138
cmd(getactorangle)			// 139
cmd(setactorangle)			// 140
cmd(mulvar)					// 141
cmd(mulvarvar)				// 142
cmd(divvar)					// 143
cmd(divvarvar)				// 144
cmd(modvar)					// 145
cmd(modvarvar)				// 146
cmd(andvar)					// 147
cmd(andvarvar)				// 148
cmd(orvar)					// 149
cmd(orvarvar)				// 150
cmd(getplayerangle)			// 151
cmd(setplayerangle)			// 152
cmd(lockplayer)				// 153
cmd(setsector)				// 154
cmd(getsector)				// 155
cmd(setactor)				// 156
cmd(getactor)				// 157
cmd(setwall)				// 158
cmd(getwall)				// 159
cmd(findnearactor)			// 160
cmd(findnearactorvar)		// 161
cmd(setactorvar)			// 162
cmd(getactorvar)			// 163
cmd(espawn)					// 164
cmd(getplayer)				// 165
cmd(setplayer)				// 166
cmd(sqrt)					// 167
cmd(eventloadactor)			// 168
cmd(espawnvar)				// 169
cmd(getuserdef)				// 170
cmd(setuserdef)				// 171
cmd(subvarvar)				// 172
cmd(subvar)					// 173
cmd(ifvarn)					// 174
cmd(ifvarvarn)				// 175
cmd(ifvarand)				// 176
cmd(ifvarvarand)			// 177
cmd(myos)					// 178
cmd(myospal)				// 179
cmd(switch)					// 180
cmd(case)					// 181
cmd(default)				// 182
cmd(endswitch)				// 183
cmd(displayrand)			// 184
cmd(sin)					// 185
cmd(xorvarvar)				// 186
cmd(xorvar)					// 187
cmd(randvarvar)				// 188
cmd(myosx) 					// 189
cmd(myospalx) 				// 190
cmd(gmaxammo) 				// 191
cmd(smaxammo) 				// 192
cmd(mapvoxel) 				// 193
cmd(startlevel) 			// 194

// RR Deer Huntin'. These are merely here for reference because the game is not supported.
// cmd(iffindnewspot)
// cmd(ifpupwind)
